# Generated by Django 2.1 on 2019-09-07 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_host', models.BooleanField(default=False)),
                ('is_info', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'db_table': 'user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Guest_info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(max_length=8)),
                ('birth_day', models.DateField(null=True)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'guest_info',
            },
        ),
        migrations.CreateModel(
            name='Hostt_info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hotel_name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('qr_code', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'host_info',
            },
        ),
    ]
