# Generated by Django 2.1 on 2019-09-07 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_info',
            name='birth_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest_info',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
