# Generated by Django 2.1 on 2019-09-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190907_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostt_info',
            new_name='Host_info',
        ),
    ]
