# Generated by Django 2.1 on 2019-09-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_info',
            field=models.BooleanField(default=False),
        ),
    ]
