# Generated by Django 2.1 on 2019-09-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=255)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
