# Generated by Django 2.1 on 2019-09-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190907_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest_info',
            old_name='user',
            new_name='user_id',
        ),
    ]
