# Generated by Django 2.1 on 2019-09-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190907_1118'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guest_info',
            table='guest_info',
        ),
    ]
